announcements.0=&8[&4Scoville&8] &7Möchten Sie einen Spieler melden? Mit &c/helpop&7 können Sie an das Personal eine Nachricht senden!
announcements.1=&8[&4Scoville&8] &7Wollen Sie Info, Ankündigungen, und Hilfe über dem Server? Tret unsere &cDiscord&7 bei! &cdiscord.gg/qnG8qa4utm
announcements.2=&8[&4Scoville&8] &7Stellen Sie sicher, dass Sie die Regeln mit &c/rules&7 lesen!
announcements.3=&8[&4Scoville&8] &7Möchten Sie einen Parcours einreichen? Mit &c#course-submission&7 in unserem Discord ist das möglich! &cdiscord.gg/qnG8qa4utm
announcements.4=&8[&4Scoville&8] &7Möchten Sie eine Einstellung ändern? Klick den &cEinstellungen&7-Kopf!
announcements.5=&8[&4Scoville&8] &7Verwenden Sie &c/prac&7, um einen Sprung zu üben!
announcements.6=&8[&4Scoville&8] &7Durch Klicken mit der &cErfahrungsfläschchen&7 können Sie die Stufenbelohnungen besichtigen!
announcements.7=&8[&4Scoville&8] &7Wenn Sie einen Parcours meistern, gibt es eine Möglichkeit, dass Sie einen &cSchillerndes-Etikett&7 bekommen!
announcements.8=&8[&4Scoville&8] &cRedstone-Lampen&7 teleportiert Sie zu deinem &cCheckpoint&7!
announcements.9=&8[&4Scoville&8] &7Im ganzem Server sind &cGeheimnisse&7 versteckt. Können Sie sie alle finden?
announcements.10=&8[&4Scoville&8] &7Wir haben &cErrungenschaften&7! Besichtigt sie in dem &cMenü&7!