announcements.0=&8[&4Scoville&8] &7Möchten Sie einen Spieler melden? Mit &c/helpop&7 können Sie an das Personal eine Nachricht senden!
announcements.1=&8[&4Scoville&8] &7Wollen Sie Info, Ankündigungen, und Hilfe über dem Server? Tret unsere &cDiscord&7 bei! &cdiscord.gg/qnG8qa4utm
announcements.2=&8[&4Scoville&8] &7Stellen Sie sicher, dass Sie die Regeln mit &c/rules&7 lesen!
announcements.3=&8[&4Scoville&8] &7Möchten Sie einen Parcours einreichen? Mit &c#course-submission&7 in unserem Discord ist das möglich! &cdiscord.gg/qnG8qa4utm
announcements.4=&8[&4Scoville&8] &7Möchten Sie eine Einstellung ändern? Klick den &cEinstellungen&7-Kopf!
announcements.5=&8[&4Scoville&8] &7Verwenden Sie &c/prac&7, um einen Sprung zu üben!
announcements.6=&8[&4Scoville&8] &7Durch Klicken mit der &cErfahrungsfläschchen&7 können Sie die Stufenbelohnungen besichtigen!
announcements.7=&8[&4Scoville&8] &7Wenn Sie einen Parcours meistern, gibt es eine Möglichkeit, dass Sie einen &cSchillerndes-Etikett&7 bekommen!
announcements.8=&8[&4Scoville&8] &cRedstone-Lampen&7 teleportiert Sie zu deinem &cCheckpoint&7!
announcements.9=&8[&4Scoville&8] &7Im ganzem Server sind &cGeheimnisse&7 versteckt. Können Sie sie alle finden?
announcements.10=&8[&4Scoville&8] &7Wir haben &cErrungenschaften&7! Besichtigt sie in dem &cMenü&7!

achievement.broadcast=&8[&{0}Scoville&8] &{0}{1}&7 hat {2}&7 erreicht!

achievement.test.name=&6&lTest &e&lErrungenschaft
achievement.test.desc=Meine Eier juckt

menu.main.title=&8Parkour-Menü

menu.main.greenhouse.title=&2&lGewächshaus
menu.main.greenhouse.desc.0=&7Betreten Sie das Gewächshaus!

menu.main.courses.title=&c&lParcours
menu.main.courses.desc.0=&7Sehen Sie die Parcours-Liste an!

menu.main.progjumps.title=&a&lProgJumps
menu.main.progjumps.desc.0=&7Rankup-ähnliches System vom Ibis Network!

menu.main.cosmetics.title=&f&lKosmetik
menu.main.cosmetics.desc.0=&7Wechseln Sie dein Etikett, deine Chatfarbe, deine Hotbar, und mehr!

menu.main.onejump.title=&6&lOneJump
menu.main.onejump.desc.0=&7Parcours mit einem Sprung pro Checkpoint!

menu.main.creative.title=&e&lKreativ
menu.main.creative.desc.0=&7Betreten Sie die Plotwelt!

menu.main.spawn.title=&b&lSpawn
menu.main.spawn.desc.0=&7Gehen Sie zurück zum Spawn!

menu.main.radio.title=&c&lRadio
menu.main.radio.desc.0=&7Hören Sie die Scoville-lieder an!

menu.main.achievements.title=&a&lErrungenschaften
menu.main.achievements.desc.0=&7Sehen Sie deine Errungenschaften an!

menu.main.levels.title=&a&lLevelbelohnungen
menu.main.levels.desc.0=&7Sehen Sie die Levelbelohnungen an!

menu.main.admin.title=&c&lAdmin-Pult
menu.main.admin.desc.0=&7Editieren Sie Serveraspekte!

menu.admin.title=&8Admin Panel

menu.admin.courses.title=&c&lCourses
menu.admin.courses.desc.0=&7Edit courses!

menu.admin.players.title=&e&lPlayers
menu.admin.players.desc.0=&7Edit player data!

menu.admin.seasons.title=&a&lSeasons
menu.admin.seasons.desc.0=&7Edit season data!

menu.generic.prev.title=&bBack
menu.generic.next.title=&bNext
menu.generic.selected.desc.0=&a&lSelected
menu.generic.selected.desc.1=&8&lNot Selected
menu.generic.confirm.title=&a&lConfirm
menu.generic.confirm.desc.0=&7Confirm these changes?

menu.courses.title=&8Parcours-Liste

menu.courses.course.diff.0=&2Süß - 1/10
menu.courses.course.diff.1=&aScharf - 2/10
menu.courses.course.diff.2=&aSchmackhaft - 3/10
menu.courses.course.diff.3=&ePikant - 4/10
menu.courses.course.diff.4=&eWürzig - 5/10
menu.courses.course.diff.5=&6Heiß - 6/10
menu.courses.course.diff.6=&6Brutzelnd - 7/10
menu.courses.course.diff.7=&cFeurig - 8/10
menu.courses.course.diff.8=&cVerbrennend - 9/10
menu.courses.course.diff.9=&4Leuchtend - 10/10

menu.courses.course.cr=&7Clear Rate
menu.courses.course.ur=Bewertung
menu.courses.course.tc=Abgeschlossen

menu.admin.courses.new=&2&lNeue Parcours

menu.admin.courses.create.prompt=&8[&eScoville&8] &7Please input the course name:
menu.admin.courses.create.title=&7Create: {0}

menu.admin.courses.create.colorname.title=&f&lColored Name
menu.admin.courses.create.colorname.desc.0=&7Click here to set the
menu.admin.courses.create.colorname.desc.1=&7colored name for the
menu.admin.courses.create.colorname.desc.2=&7course in the GUI!
menu.admin.courses.create.colorname.desc.3=&7Currently: {0}
menu.admin.courses.create.colorname.prompt=&8[&eScoville&8] &7Please input the course name &ewith colors&7:

menu.admin.courses.create.guiitem.title=&f&lGUI Item
menu.admin.courses.create.guiitem.desc.0=&7Place an item here to
menu.admin.courses.create.guiitem.desc.1=&7set the item to be
menu.admin.courses.create.guiitem.desc.2=&7used in the GUI!

menu.admin.courses.create.authors.title=&f&lAuthors
menu.admin.courses.create.authors.desc.0=&7Click here to select
menu.admin.courses.create.authors.desc.1=&7the course authors!
menu.admin.courses.create.authors.desc.3=&7Currently: {0}

menu.admin.courses.create.diff.title=&{0}&lDifficulty: {1}
menu.admin.courses.create.rank.title=&{0}&lRank: {1}

menu.admin.courses.create.hallway.title=&e&lHallways
menu.admin.courses.create.rankup.title=&f&lRankup
menu.admin.courses.create.open.title=&a&lOpen