announcements.0=&8[&4Scoville&8] &7Masz gracza do zgłoszenia? Wyślij wiadomość do personelu online za pomocą &c/helpop&7!
announcements.1=&8[&4Scoville&8] &7Want to get info, updates, and help on the server? Join our &cDiscord&7! &cdiscord.gg/qnG8qa4utm
announcements.2=&8[&4Scoville&8] &7Make sure to read the &c/rules&7!
announcements.3=&8[&4Scoville&8] &7Want to submit a &ccourse&7? Do so in &c#course-submission &7in our &cDiscord&7! &cdiscord.gg/qnG8qa4utm
announcements.4=&8[&4Scoville&8] &7Want to change a setting? Click the &cOptions &7head!
announcements.5=&8[&4Scoville&8] &7Use &c/prac &7to practice a jump!
announcements.6=&8[&4Scoville&8] &7Level rewards can be viewed in the menu by clicking the &cexperience bottle&7!
announcements.7=&8[&4Scoville&8] &7Beating a course gives a slight chance at obtaining a &cshiny tag&7!
announcements.8=&8[&4Scoville&8] &cRedstone lamps &7teleport you back to your &ccheckpoint&7!
announcements.9=&8[&4Scoville&8] &7There are &csecrets &7throughout the server. Can you find them all?
announcements.10=&8[&4Scoville&8] &7We have &cachievements&7! View them in the &cmenu&7!